spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka
zuul:
  routes:
    api-movie:
      path: /api/**
      service-id: FEIGN-MOVIE-CONSUMER
server:
  port: 8000
