spring:
  application:
    name: source
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.20.5.79:9092
          zkNodes: 172.20.5.79:2181
      bindings:
        products:
          destination: transformed
#          content-type: text/plain
#          producer:
#            partitionCount: 1
server:
  port: 8081