spring:
  application:
    name: config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mark0614/springCloudLearning.git
          username: mark0614@126.com
          password: mln830911
          search-paths: /chapter-1-5/config-repo
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka