
#eureka:
#  server:
#    enable-self-preservation: false # 关闭eureka自我保护机制
#    eviction-interval-timer-in-ms: 30000  # 清理服务注册表的时间间隔，单位：毫秒
#  client:
#    fetch-registry: false # 是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false
#    register-with-eureka: false
spring:
  application:
    name: eureka-server # 表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false
---
spring:
  profiles: node-1
server:
  port: 8761  #服务端口
eureka:
  instance:
    hostname: eureka-server-1
  client:
    serviceUrl:
      defaultZone: http://eureka-server-2:8762/eureka,http://eureka-server-3:8763/eureka  # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔

---
spring:
  profiles: node-2
server:
  port: 8762  #服务端口
eureka:
  instance:
    hostname: eureka-server-2
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:8761/eureka,http://eureka-server-3:8763/eureka  # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔

---
spring:
  profiles: node-3
server:
  port: 8763  #服务端口
eureka:
  instance:
    hostname: eureka-server-3
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:8761/eureka,http://eureka-server-2:8762/eureka  # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔

