spring:
  application:
    name: movie-service
server:
  port: 8080
eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 30