spring:
  application:
    name: movie-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 30
---
spring:
  profiles: node-1
server:
  port: 8080
---
spring:
  profiles: node-2
server:
  port: 8081