spring:
  application:
    name: config-server-bus
  cloud:
      config:
        server:
          git:
            uri: https://github.com/mark0614/springCloudLearning.git
            username: mark0614@126.com
            password: mln830911
            search-paths: /chapter-1-8/config-repo
      stream:
        kafka:
          binder:
            brokers: 172.20.5.79:9092
            zk-nodes: 172.20.5.79:2181
server:
  port: 9000
eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka
management:
  security:
    enabled: false