spring:
  application:
    name: sink
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.20.5.79:9092
          zk-nodes: 172.20.5.79:2181
      bindings:
        orders:
          destination: transformed
#          group: s1
#          consumer:
#            autoCommitOffset: false
#            concurrency: 1
#            partitioned: false
#logging:
#  level:
#    org:
#      apache:
#        kafka: debug